#!/bin/sh
#
# Init oled module
# source in https://github.com/armlabs/ssd1306_linux
#

DAEMON="Oled Module"

i2ctest() {
	echo "scan /dev/i2c-0 :"
	# i2c device probe
	i2cdetect -y -r 0
	echo
}

start() {
	printf 'Initialize %s...\n' "$DAEMON"

	i2ctest

	# OLED init
	ssd1306_bin -I 128x64

	# clear whole screen
	ssd1306_bin -c

	# normal orientation display
	ssd1306_bin -r 0

	# turn on display
	ssd1306_bin -d 1

	# write string
	ssd1306_bin -l "Hi F1C200s"

	return 0
}

stop() {
	printf 'Stopping %s...\n' "$DAEMON"

        # clear whole screen
        ssd1306_bin -c

	return 0
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

